version: 2.1

jobs:
    unit-test:
        docker:
            -   image: cimg/node:18.13
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - node-v1-{{ checksum "package-lock.json" }}
                        - node-v1-
            -   run: npm ci --no-audit --prefer-offline
            -   save_cache:
                    key: node-v1-{{ checksum "package-lock.json" }}
                    paths:
                        - node_modules
            -   run:
                    name: "Run Unit Tests"
                    command: npm run test

    compile:
        docker:
            -   image: cimg/node:18.13
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - node-v1-{{ checksum "package-lock.json" }}
                        - node-v1-
            -   run: npm ci --no-audit --prefer-offline
            -   save_cache:
                    key: node-v1-{{ checksum "package-lock.json" }}
                    paths:
                        - node_modules
            -   run: npm run build

    build-and-deploy:
        docker:
            -   image: cimg/node:18.13
        steps:
            - checkout
            - setup_remote_docker
            -   run:
                    name: Build Docker Image
                    command: |
                        npm ci --no-audit --prefer-offline
                        npm run build
                        docker build -t ipwnpancakes/vinyl-cd-emporium:latest .
                        echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                        docker push ipwnpancakes/vinyl-cd-emporium:latest

workflows:
    test-and-build-and-deploy:
        jobs:
            - unit-test
            - compile
            -   build-and-deploy:
                    requires:
                        - unit-test
                        - compile
                    filters:
                        branches:
                            only:
                                - master
