version: 2.1

jobs:
    unit-test:
        docker:
            -   image: cimg/node:18.13
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - node-v1-{{ checksum "package-lock.json" }}
                        - node-v1-
            -   run: npm ci --no-audit --prefer-offline
            -   save_cache:
                    key: node-v1-{{ checksum "package-lock.json" }}
                    paths:
                        - node_modules
            -   run:
                    name: "Run Unit Tests"
                    command: npm run test

    compile:
        docker:
            -   image: cimg/node:18.13
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - node-v1-{{ checksum "package-lock.json" }}
                        - node-v1-
            -   run: npm ci --no-audit --prefer-offline
            -   save_cache:
                    key: node-v1-{{ checksum "package-lock.json" }}
                    paths:
                        - node_modules
            -   run: npm run build

workflows:
    run-commit-tests:
        jobs:
            - unit-test
    compile-app:
        jobs:
            - compile
